#!/usr/bin/env bash

# Dart Format

printf "\e[33;1m%s\e[0m\n" 'Running dart format.'

result=$(dart format lib)
result_lines=$(echo "$result" | wc -l)

if [ "$result_lines" -gt 1 ]; then
  echo "$result"
  printf "\e[31;1m%s\e[0m\n" 'Dart format applied changes, please commit again.'
  exit 1
fi

echo "$result"
printf "\e[32;1m%s\e[0m\n" 'Finished running dart format.'

# Get the commit message.

COMMIT_MSG=$(git log -1 --pretty=%B)

# 20260123 gjw Check if the commit message starts with 'Bump version'
# If it does then run `make versions` to update the version in any
# files that require updating, based on the version from pubspec.yaml.
# Then add any updated files to the commit. I add specific files
# rather than using `.` just to avoid possibly adding things I was not
# planning to. This way we always update, for example, the snap
# version when we 'Bump version', avoiding missing this step, so the
# installer builds that 'Bump version' triggers will get the correct
# versions.

if [[ $COMMIT_MSG == Bump\ version* ]]; then
    printf "\e[33;1m%s\e[0m\n" 'Update versions.'

    make versions
    git add snap/snapcraft.yaml

    printf "\e[32;1m%s\e[0m\n" 'Finished updating versions.'

fi
