name: todopod
description: "ToDo List Management with Secure and Private Storage"
publish_to: 'none'
version: 0.1.6+1

environment:
  sdk: ^3.11.3

dependencies:
  file_picker: any
  flutter:
    sdk: flutter
  gap: any
  provider: any
  solidui: ^0.3.8
  solidpod: ^0.12.2
  uuid: any

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/images/app_icon.png
  uses-material-design: true

# Define launcher icons for all platforms (except Linux) so icons for
# the apps can be automatically updated using:
#
# `dart run flutter_launcher_icons`
#
# (gjw 20250429)

flutter_launcher_icons:
  image_path: "assets/images/app_icon.png"
  android: true
  min_sdk_android: 21
  ios: true
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  macos:
    generate: true
  web:
    generate: true
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    icon_size: 48 # min:48, max:256, default: 48
