name: todopod
description: "ToDo List Management with Secure and Private Storage"
publish_to: 'none'
version: 0.1.1+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  gap: any
  provider: any
  solidui: 0.3.8
  uuid: any
  solidpod: any
  file_picker: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
